CREATE TABLE IF NOT EXISTS actions (
  ISIN CHAR(12) NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  market VARCHAR(50) NOT NULL,
  activitySector VARCHAR(50) NOT NULL,
  currentPrice DECIMAL(15,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  isAvailable TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NULL
) 
