CREATE TABLE IF NOT EXISTS savings_rates (
    id VARCHAR(36) PRIMARY KEY,
    rate DECIMAL(5,2) NOT NULL,
    effectiveDate DATETIME NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
