import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle, DrawerTrigger } from "@/components/ui/drawer";
import { Separator } from "@/components/ui/separator";
import { CircleX, Menu } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="px-4 py-6 xl:py-8 md:px-13 xl:px-30">
      <div className="flex items-center justify-between mb-4 xl:mb-6">
        <div className="flex items-center gap-3">
          <Avatar>
            <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
          <div>
            <p className="text-sm text-muted-foreground">Bonjour 👋</p>
            <p className="font-semibold text-lg">Cécel</p>
          </div>
        </div>
        <Drawer direction="right">

          <DrawerTrigger asChild>
            <Button variant="ghost" size="icon">
              <Menu className="h-5 w-5 text-muted-foreground" />
            </Button>
          </DrawerTrigger>
          <DrawerContent>
            <DrawerHeader className="flex justify-between flex-row">
              <div>
                <DrawerTitle>A.V.E.N.I.R</DrawerTitle>
                <DrawerDescription>Menu</DrawerDescription>
              </div>
              <DrawerClose ><CircleX /></DrawerClose>
            </DrawerHeader>
            <Separator />
            <div className="flex flex-col items-start">
              <Button variant="link" asChild>
                <Link href={"/accounts"} >Account</Link>
              </Button>

              <Button variant="link" asChild>
                <Link href={"/accounts"} >Account</Link>
              </Button>

              <Button variant="link" asChild>
                <Link href={"/accounts"} >Account</Link>
              </Button>

            </div>
            <DrawerFooter>
              <Button>Déconnexion</Button>
            </DrawerFooter>
          </DrawerContent>
        </Drawer>
      </div>
      {children}
    </main>
  );
}
