export const rawActions = [
  {
    ISIN: "US0378331005",
    name: "Apple Inc.",
    totalNb: 100,
    symbol: "AAPL",
    market: "NASDAQ",
    activitySector: "Technology",
    current_price: 182.55,
    currency: "USD",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "US0231351067",
    name: "Amazon.com Inc.",
    totalNb: 8,
    symbol: "AMZN",
    market: "NASDAQ",
    activitySector: "E-Commerce",
    current_price: 155.12,
    currency: "USD",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "US5949181045",
    name: "Microsoft Corp.",
    totalNb: 12,
    symbol: "MSFT",
    market: "NASDAQ",
    activitySector: "Software",
    current_price: 320.1,
    currency: "USD",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "FR0000120271",
    name: "TotalEnergies SE",
    totalNb: 2,
    symbol: "TTE",
    market: "Euronext Paris",
    activitySector: "Energy",
    current_price: 63.45,
    currency: "EUR",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "FR0000131104",
    name: "LVMH Moët Hennessy Louis Vuitton",
    totalNb: 50,
    symbol: "MC",
    market: "Euronext Paris",
    activitySector: "Luxury Goods",
    current_price: 765.2,
    currency: "EUR",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "US30303M1027",
    name: "Meta Platforms Inc.",
    totalNb: 20,
    symbol: "META",
    market: "NASDAQ",
    activitySector: "Social Media",
    current_price: 289.34,
    currency: "USD",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "US02079K3059",
    name: "Alphabet Inc. Class A",
    totalNb: 1,
    symbol: "GOOGL",
    market: "NASDAQ",
    activitySector: "Technology",
    current_price: 132.76,
    currency: "USD",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "US88160R1014",
    name: "Tesla Inc.",
    totalNb: 6,
    symbol: "TSLA",
    market: "NASDAQ",
    activitySector: "Automotive",
    current_price: 242.3,
    currency: "USD",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "JP3436100006",
    name: "Sony Group Corporation",
    totalNb: 23,
    symbol: "SONY",
    market: "Tokyo Stock Exchange",
    activitySector: "Electronics",
    current_price: 118.4,
    currency: "JPY",
    isAvailable: true,
    createdAt: new Date(),
  },
  {
    ISIN: "CH0038863350",
    name: "Nestlé SA",
    totalNb: 19,
    symbol: "NESN",
    market: "SIX Swiss Exchange",
    activitySector: "Food & Beverage",
    current_price: 105.25,
    currency: "CHF",
    isAvailable: true,
    createdAt: new Date(),
  },
];
