export const rawFormuleCredits = [
  {
    type: "IMMOBILIER",
    label: "Prêt Immobilier Classique",
    description:
      "Crédit immobilier standard pour l'achat de votre résidence principale",
    interestRate: 3.5,
    insuranceRate: 0.36,
    minAmount: 50000,
    maxAmount: 500000,
    currency: "EUR",
    isActive: true,
  },
  {
    type: "IMMOBILIER",
    label: "Prêt Primo-Accédant",
    description:
      "Offre spéciale pour les premiers acheteurs avec taux préférentiel",
    interestRate: 3.0,
    insuranceRate: 0.3,
    minAmount: 30000,
    maxAmount: 300000,
    currency: "EUR",
    isActive: true,
  },
  {
    type: "IMMOBILIER",
    label: "Prêt Investissement Locatif",
    description: "Crédit pour l'acquisition d'un bien destiné à la location",
    interestRate: 4.0,
    insuranceRate: 0.4,
    minAmount: 80000,
    maxAmount: 800000,
    currency: "EUR",
    isActive: true,
  },
  {
    type: "IMMOBILIER",
    label: "Prêt Travaux",
    description: "Financement pour vos travaux de rénovation et d'amélioration",
    interestRate: 4.5,
    insuranceRate: 0.25,
    minAmount: 5000,
    maxAmount: 75000,
    currency: "EUR",
    isActive: true,
  },

  {
    type: "CONSOMMATION",
    label: "Crédit Personnel",
    description: "Prêt personnel pour tous vos projets",
    interestRate: 5.0,
    insuranceRate: 0.4,
    minAmount: 1000,
    maxAmount: 50000,
    currency: "EUR",
    isActive: true,
  },
  {
    type: "CONSOMMATION",
    label: "Crédit Renouvelable",
    description: "Réserve d'argent disponible à tout moment",
    interestRate: 8.0,
    insuranceRate: 0.5,
    minAmount: 500,
    maxAmount: 15000,
    currency: "EUR",
    isActive: true,
  },

  {
    type: "PROFESSIONNEL",
    label: "Crédit Professionnel Équipement",
    description: "Financement pour l'achat de matériel professionnel",
    interestRate: 3.8,
    insuranceRate: 0.3,
    minAmount: 10000,
    maxAmount: 200000,
    currency: "EUR",
    isActive: true,
  },
  {
    type: "PROFESSIONNEL",
    label: "Crédit Trésorerie Entreprise",
    description: "Solution pour gérer votre trésorerie d'entreprise",
    interestRate: 5.5,
    insuranceRate: 0.45,
    minAmount: 5000,
    maxAmount: 100000,
    currency: "EUR",
    isActive: true,
  },

  {
    type: "AUTO",
    label: "Crédit Auto Neuf",
    description: "Financement pour l'achat de votre véhicule neuf",
    interestRate: 4.0,
    insuranceRate: 0.3,
    minAmount: 5000,
    maxAmount: 75000,
    currency: "EUR",
    isActive: true,
  },
  {
    type: "AUTO",
    label: "Crédit Auto Occasion",
    description: "Financement pour l'achat de votre véhicule d'occasion",
    interestRate: 4.5,
    insuranceRate: 0.35,
    minAmount: 3000,
    maxAmount: 50000,
    currency: "EUR",
    isActive: true,
  },

  {
    type: "AUTRE",
    label: "Prêt Étudiant",
    description: "Crédit à taux préférentiel pour financer vos études",
    interestRate: 1.5,
    insuranceRate: 0.15,
    minAmount: 1000,
    maxAmount: 45000,
    currency: "EUR",
    isActive: true,
  },
  {
    type: "AUTRE",
    label: "Prêt Écologique",
    description: "Financement pour vos projets de transition énergétique",
    interestRate: 2.0,
    insuranceRate: 0.2,
    minAmount: 3000,
    maxAmount: 30000,
    currency: "EUR",
    isActive: true,
  },

  {
    type: "CONSOMMATION",
    label: "Crédit Loisirs (Ancienne formule)",
    description: "Ancienne offre crédit loisirs - Non disponible",
    interestRate: 6.0,
    insuranceRate: 0.4,
    minAmount: 2000,
    maxAmount: 25000,
    currency: "EUR",
    isActive: false,
  },
] as const;
