import SessionInfo from '@/components/SessinInfo';

import { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { authOptions } from '../api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';
import { MenuDrawer } from './MenuDrawer';
import { MenuPopover } from './MenuPopover';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  if (!session) redirect('/login');
  if (session.user.role !== 'client') redirect('/unauthorized');
  return (
    <main className="px-4 py-6 xl:py-8 md:px-13 xl:px-30">
      <div className="flex items-center justify-between mb-4 xl:mb-6">
        <SessionInfo />
        <div className='flex gap-5'>
          <MenuPopover />
          <MenuDrawer />
        </div>
      </div>
      {children}
    </main>
  );
}


