import { Color } from "@domain/values/Color";

export const rawClients = [
  {
    firstname: "client",
    lastname: "client",
    email: "client@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "blue" as const,
        balance: 1500,
        currency: "EUR",
        transactions: [
          {
            amount: 500,
            currency: "EUR",
            type: "debit" as const,
            label: "Salaire",
            date: new Date("2025-10-28T10:00:00Z"),
            icon: "💰",
          },
          {
            amount: 50,
            currency: "EUR",
            type: "debit" as const,
            label: "Courses",
            date: new Date("2025-10-29T14:30:00Z"),
            icon: "🛒",
          },
        ],
      },
      {
        name: "Compte épargne",
        type: "epargne" as const,
        color: "red" as const,
        balance: 5000,
        currency: "EUR",
        transactions: [
          {
            amount: 200,
            currency: "EUR",
            type: "credit" as const,
            label: "Prime",
            date: new Date("2025-10-30T08:00:00Z"),
            icon: "🏆",
          },
        ],
      },
    ],
  },
  {
    firstname: "Benjamin",
    lastname: "Martin",
    email: "benjamin.martin@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "blue" as const,
        balance: 1200,
        currency: "EUR",
        transactions: [
          {
            amount: 300,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-25T09:00:00Z"),
            icon: "💰",
          },
          {
            amount: 75,
            currency: "EUR",
            type: "debit" as const,
            label: "Facture Internet",
            date: new Date("2025-10-26T12:00:00Z"),
            icon: "🌐",
          },
        ],
      },
    ],
  },
  {
    firstname: "Claire",
    lastname: "Leroy",
    email: "claire.leroy@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "purple" as string,
        balance: 900,
        currency: "EUR",
        transactions: [
          {
            amount: 400,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-27T10:00:00Z"),
            icon: "💰",
          },
          {
            amount: 60,
            currency: "EUR",
            type: "debit" as const,
            label: "Courses",
            date: new Date("2025-10-28T14:00:00Z"),
            icon: "🛒",
          },
        ],
      },
    ],
  },
  {
    firstname: "David",
    lastname: "Moreau",
    email: "david.moreau@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "orange" as const,
        balance: 1100,
        currency: "EUR",
        transactions: [
          {
            amount: 500,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-25T09:00:00Z"),
            icon: "💰",
          },
          {
            amount: 120,
            currency: "EUR",
            type: "debit" as const,
            label: "Essence",
            date: new Date("2025-10-26T11:30:00Z"),
            icon: "⛽",
          },
        ],
      },
    ],
  },
  {
    firstname: "Emma",
    lastname: "Bernard",
    email: "emma.bernard@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "pink" as const,
        balance: 1300,
        currency: "EUR",
        transactions: [
          {
            amount: 450,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-27T08:00:00Z"),
            icon: "💰",
          },
          {
            amount: 80,
            currency: "EUR",
            type: "debit" as const,
            label: "Restaurant",
            date: new Date("2025-10-28T20:00:00Z"),
            icon: "🍽️",
          },
        ],
      },
    ],
  },
  {
    firstname: "Florent",
    lastname: "Girard",
    email: "florent.girard@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "green" as const,
        balance: 1000,
        currency: "EUR",
        transactions: [
          {
            amount: 400,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-28T09:00:00Z"),
            icon: "💰",
          },
          {
            amount: 50,
            currency: "EUR",
            type: "debit" as const,
            label: "Courses",
            date: new Date("2025-10-29T15:00:00Z"),
            icon: "🛒",
          },
        ],
      },
    ],
  },
  {
    firstname: "Julie",
    lastname: "Mercier",
    email: "julie.mercier@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "red" as const,
        balance: 950,
        currency: "EUR",
        transactions: [
          {
            amount: 500,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-28T10:00:00Z"),
            icon: "💰",
          },
          {
            amount: 70,
            currency: "EUR",
            type: "debit" as const,
            label: "Shopping",
            date: new Date("2025-10-29T12:00:00Z"),
            icon: "🛍️",
          },
        ],
      },
    ],
  },
  {
    firstname: "Kevin",
    lastname: "Renaud",
    email: "kevin.renaud@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "orange" as const,
        balance: 1400,
        currency: "EUR",
        transactions: [
          {
            amount: 600,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-27T09:00:00Z"),
            icon: "💰",
          },
          {
            amount: 100,
            currency: "EUR",
            type: "debit" as const,
            label: "Essence",
            date: new Date("2025-10-28T18:00:00Z"),
            icon: "⛽",
          },
        ],
      },
    ],
  },
  {
    firstname: "Lucie",
    lastname: "Petit",
    email: "lucie.petit@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "green" as const,
        balance: 1150,
        currency: "EUR",
        transactions: [
          {
            amount: 500,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-28T09:30:00Z"),
            icon: "💰",
          },
          {
            amount: 60,
            currency: "EUR",
            type: "debit" as const,
            label: "Courses",
            date: new Date("2025-10-29T14:00:00Z"),
            icon: "🛒",
          },
        ],
      },
    ],
  },
  {
    firstname: "Maxime",
    lastname: "Robert",
    email: "maxime.robert@example.com",
    password: "password123",
    accounts: [
      {
        name: "Compte courant",
        type: "courant" as const,
        color: "gray" as const,
        balance: 1300,
        currency: "EUR",
        transactions: [
          {
            amount: 700,
            currency: "EUR",
            type: "credit" as const,
            label: "Salaire",
            date: new Date("2025-10-28T08:00:00Z"),
            icon: "💰",
          },
          {
            amount: 90,
            currency: "EUR",
            type: "debit" as const,
            label: "Restaurant",
            date: new Date("2025-10-29T19:00:00Z"),
            icon: "🍽️",
          },
        ],
      },
    ],
  },
];
