import { ThemeToggleSwitch } from '@/components/ThemeToogleButton';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <main className='px-4 md:px-60 xl:px-120 py-6 xl:py-8' >
      <div className=" flex  justify-end mb-4">
        <ThemeToggleSwitch />
      </div>
      {children}
    </main>
  );
}
